### ISSUE TITLE
Cannot read properties of undefined (reading 'off')

### ISSUE THREAD

**Issue by ludiguo** [jodit/jodit-react#191] opened 2022-05-13 09:47 UTC
Is there an error in this installation package, or is it a problem that I haven't configured well in my project? It was good before, and suddenly reported an error

**Comment by xdan** [comment] 2022-05-13 10:03
Can you show me stack trace?

**Comment by vimutti77** [comment] 2022-05-13 10:20
This is a reproducible example https://codesandbox.io/s/jodit-react-event-bug-on-unmount-forked-57mlv1

If you click on unmount jodit button, It will throw an error.

**Comment by rafaelfndev** [comment] 2022-05-13 18:53
I just upgrade to version 1.3.5 to use [onPaste method](https://github.com/jodit/jodit-react/issues/189#issuecomment-1125288423) and now I get this error too.

![Screenshot_41](https://user-images.githubusercontent.com/7171869/168349410-4142d72f-cc60-4233-b791-9f1e9ef65f1f.png)

**Comment by rouftom** [comment] 2022-05-15 01:31
This error occurs because events related to the JoditEditor component are not remembered when react renders. For that, you can use react's useMemo to fix the issue as follows: 

`import * as React from 'react`

`const handleJoditOnBlur = React.useMemo((newContent) => {
    // Deal with the new content
})`

`const handleJoditOnChange = React.useMemo((newContent) => {
    // Deal with the new content
})`



`<JoditEditor
    config={config}
    value={value}
    onBlur={handleJoditOnBlur}
    onChange={handleJoditOnChange}
/>`

**Comment by haimbrum** [comment] 2022-05-15 09:30
Looks like the problem is caused as a result of a bad cleanup.

@xdan issue is introduce on this commit: https://github.com/jodit/jodit-react/commit/7bc5d7e9683ec786c861ddbb9118137df532e582 
I'm not sure why but it appears that on the cleanup callback we don't have a reference to the events object anymore.

![image](https://user-images.githubusercontent.com/25712221/168465218-86c8cd39-9923-49e2-805e-0662a61a6acd.png)

**Comment by xdan** [comment] 2022-05-15 10:32
Fixed in 1.3.6

**Closed by xdan** 2022-05-15 10:32 UTC
Labels: bug, wip
